# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Riakg < Formula
  desc "A command-line interface for the Riak database through its HTTP API"
  homepage "https://github.com/heavyblade/riakg"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Heavyblade/Riakg/releases/download/v0.3.0/Riakg_0.3.0_Darwin_arm64.tar.gz"
      sha256 "e92dbfc3245c526053b17cb15438bb5aa41f613629d42715238ad8297dfcda59"

      def install
        bin.install "Riakg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Heavyblade/Riakg/releases/download/v0.3.0/Riakg_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "3dc676e2fa009ad7f7493e44b3c4b09a0f1c6dc84c65a515c6fa08b44792fb0e"

      def install
        bin.install "Riakg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Heavyblade/Riakg/releases/download/v0.3.0/Riakg_0.3.0_Linux_arm64.tar.gz"
      sha256 "76e24cd9bf37e6cef451a1ec88f160c85faec12b3834bf82bae3d5b51ba2abc7"

      def install
        bin.install "Riakg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Heavyblade/Riakg/releases/download/v0.3.0/Riakg_0.3.0_Linux_x86_64.tar.gz"
      sha256 "33c9d3a323d3149007fadd66a0a00883c4d844f07250478978bfd6f5bd3b855c"

      def install
        bin.install "Riakg"
      end
    end
  end
end
